### ISSUE TITLE
Large values are not properly formatted

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/js-sdk#124] opened 2022-09-20 18:34 UTC
Example: 

```
formatAmountForDisplay(1000000000000000000, false) == 1.00
formatAmountForDisplay(2000000000000000, true) == 0.002
formatAmountForDisplay(2.222002e+21, true) == 0.0000002.222002e+21
```

**Comment by nop33** [comment] 2022-10-24 07:39
First of all, all examples above are using a number and not a bigint as input to the function. That is not correct, since the function expects a bigint argument.

> formatAmountForDisplay(1000000000000000000, false) == 1.00

Secondly, I don't understand why this is wrong. It's 1 with 18 zeros. So, the value 1.00 is correct. We have tests for this.

> formatAmountForDisplay(2000000000000000, true) == 0.002

Thirdly, this also seems to be correct. 15 zeros move the point 3 steps to the left, so the number seems correct. We also have tests for this.

> formatAmountForDisplay(2.222002e+21, true) == 0.0000002.222002e+21

This is just wrong, the function doesn't accept number.

I am closing this as not reproducable.

/cc @mvaivre

**Closed by nop33** 2022-10-24 07:39 UTC
Labels: bug
